crazy-max/docker-rtorrent-rutorrent

Dockerfile
libxml2 and libxslt is missing and required to build the dockerimage.
So i added the libraries libxml2 and libxslt to build the nginx module.
=> LibXML2 and LibXSLT are missing!

entrypoint.sh
When running the container with an empty data directory the torrent directory was not being created. In that state no new torrents could be added via the ruTorrent UI.
=> Create torrent directory in rutorrent directory.

rootfs/etc/cont-init.d/03-config.sh
The plugin broke with 5902ca9 when changing to python 3
`pip` is needed to be kept installed, and python path added to `$pathToExternals`
=> Fix cloudflare plugin

rootfs/tpls/etc/rtorrent/.rtlocal.rc
Fixes #71 
Add the execute command to initialize the ruTorrent plugins on launch.
Directory structure of a clean launch without the command:
```
$ tree data/rutorrent/share/
data/rutorrent/share/
├── torrents
└── users
2 directories, 0 files
```
Directory structure of a clean launch with the command:
```
$ tree data/rutorrent/share/
data/rutorrent/share/
├── torrents
└── users
└── rtorrent
├── settings
│   ├── erasedata
│   ├── extsearch.dat
│   ├── loginmgr.dat
│   ├── rss
│   │   └── cache
│   │       └── info
│   ├── rtorrent.dat
│   ├── scheduler.dat
│   └── trafic
│       ├── torrents
│       └── trackers
└── torrents
11 directories, 5 files
```
=> Initialize ruTorrent plugins on launch

rootfs/etc/cont-init.d/03-config.sh
Unfortunately,
```
dig +short myip.opendns.com @resolver1.opendns.com
```
does not return anything when routing the traffic through certain VPN providers.
Especially using a VPN is a situation where automatic determination of `$WAN_IP` is important, though.
How about adding a fallback by using `curl ifconfig.me`?
=> ifconfig.me as fallback for automatic WAN_IP determination

Dockerfile
First of all - you made a great rtorrent/rutorrent container, thanks for sharing :)
I wanted to use it along with autodl-irssi and it's rutorrent plugin. However, I run into a problem where the rutorrent plugin could not initialize properly (could not read configuration files). During troubleshooting I found it it was due to missing php-posix library in the container. The responsible line is:
https://github.com/autodl-community/autodl-rutorrent/blob/ffeebe104cdfe309b96f40ebb574840a877f367c/getConf.php#L42
I confirmed the fix is working by building a test container with this library as an additional layer on top:
```
FROM crazymax/rtorrent-rutorrent:latest
RUN apk --update --no-cache add php7-posix
```
So I thought I'd make a pull request as well. Would you consider including this into …
=> Added php posix library for autodl plugin

README.md, rootfs/etc/cont-init.d/03-config.sh, rootfs/tpls/.rtorrent.rc, rootfs/tpls/etc/nginx/conf.d/rpc.conf, rootfs/tpls/etc/rtorrent/.rtlocal.rc
By default, NGINX only allows body's of 1M. Currently, there is a setting in the .rtorrent.rc file for XMLRPC size limit, which is only effective below 1M because above 1M, NGINX steps in and disallows the request with error 413 Request Entity Too Large.
=> Added XMLRPC_SIZE_LIMIT as a global option

examples/traefik/docker-compose.yml
Fixes #81 
Resolve problems with container runtime
```
rtorrent-rutorrent_geoip-updater_1 exited with code 1
traefik_1             | time="2021-07-26T00:20:52Z" level=error msg="Could not define the service name for the router: too many services" providerName=docker routerName=rutorrent
traefik_1             | time="2021-07-26T00:20:52Z" level=error msg="Could not define the service name for the router: too many services" providerName=docker routerName=webdav
traefik_1             | time="2021-07-26T00:20:52Z" level=info msg="Skipping same configuration" providerName=docker
traefik_1             | time="2021-07-26T00:20:53Z" level=error msg="HTTP challenge is not enabled" routerName=acme-http@internal entryPointName=http
traefik_1             | time="2021-07-26T00:21:06Z" level=error …
```
=> Add service labels for http.routers

Dockerfile
Set S6_KILL_GRACETIME to 10 seconds in order to give ample time to rtorrent to shutdown properly before being SIGKILL
fixes #140
fixes #123
=> Set S6_KILL_GRACETIME to 10 seconds

Dockerfile
`xmlrpc-c` is not configured properly. It will cause a very significant performance regression, if the `wininet` and `libwww` clients are not disabled. We want `xmlrpc-c` to use `curl` because it's razor fast and stable. These changes require testing before being merged. I don't have time to test it. The change value is of high importance, which is why I rushed the pull request.
=> Configure xml-rpc correctly

Dockerfile
rTorrent, libTorrent and xmlrpc support link time optimizations. It's safe to do this. Make rTorrent and libTorrent with Level 2 optimizations. (default is no optimization) This significantly improves performance and reduces code size.
=> Make rtorrent and libtorrent with -O2 -flto

rootfs/tpls/etc/rtorrent/.rtlocal.rc
Needed to bump php7 to php81 to match the installed version, so rutorrent plugins can initialise properly.
=> Bump php version in .rtlocal.rc

Dockerfile, rootfs/etc/cont-init.d/03-config.sh
fixes https://github.com/crazy-max/docker-rtorrent-rutorrent/issues/178
closes #205 
Update ruTorrent to v4.0-stable: https://github.com/Novik/ruTorrent/releases/tag/v4.0-stable cc @stickz
[geoip2-rutorrent](https://github.com/Micdu70/geoip2-rutorrent) is not (yet) compatible with ruTorrent 4 so needs to disable it in the meantime cc @Micdu70:
```
2023/01/07 20:54:10 [error] 550#550: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function getPluginConf() in /var/www/rutorrent/plugins/geoip2/init.php:11
Stack trace:
#0 /var/www/rutorrent/php/getplugins.php(496): require_once()
#1 {main}
```
=> ruTorrent v4.0-stable

rootfs/tpls/.rtorrent.rc
This workaround is no longer desirable, as discussed here: https://github.com/crazy-max/docker-rtorrent-rutorrent/pull/225#issuecomment-1500285041
closes #199
closes #203
closes #225
=> Remove erase data workaround

Dockerfile
The `php81-dom` extension is required for ruTorrent v4.1 to function properly. https://github.com/Novik/ruTorrent/issues/2500
`v4.1.3` throws an error when trying to update RSS Feeds. `v4.1.4` will be released next and fix this issue. However, it's still highly recommended to include this extension for optimization. See #236. It wasn't enough to just include `php81-xml`. Alpine puts the DOM module into a separate package. Mentioning PR https://github.com/Novik/ruTorrent/pull/2498 as well for reference.
=> Install php81-dom for ruTorrent v4.1

Dockerfile
Compile curl and c-ares with level 2 optimizations and link time optimizations. Pipe curl because it barely takes any memory.
=> Curl: Add building optimizations

README.md, rootfs/etc/cont-init.d/03-config.sh, rootfs/tpls/etc/rtorrent/.rtlocal.rc
This commit improves session saving support for rTorrent to prevent unnecessary loss of torrent files. It also increases the session saving interval from 20 minutes to 1 hour to reduce disk i/o usage with thousands of torrents. Session saving is a very intensive task. Torrents fail to save into session by default when added and can be lost if a crash occurs between saving intervals.
=> rTorrent: Improve session saving

Dockerfile, patches/libtorrent/throttle-fix-0.13.8.patch, patches/rtorrent/lockfile-fix.patch, patches/rtorrent/scgi-fix.patch, patches/rtorrent/session-file-fix.patch, patches/rtorrent/xmlrpc-fix.patch, patches/rtorrent/xmlrpc-logic-fix.patch
This commit adds multiple stability patches to rtorrent. I have tested these for multiple months. The reason for modifying the software is to resolve stability issues. The software owner is no longer releasing new versions.
**libtorrent**
- Fixes an issue where the throttle plugin on ruTorrent is required to limit upload/download speed to 1gbps.
**rTorrent**
- Fixes a crash caused by some hardening flags during the build process.
- Fixes a crash caused by ruTorrent sending invalid xmlrpc data to rTorrent.
- Fixes a crash caused by external configurations sending invalid xmlrpc data to rTorrent.
- Fixes an issue where torrent information will not update if too many torrents are running.
- Fixes an issue where a power loss during torrent session saving will corrupt torrents.
=> rTorrent: Add stability patches

Dockerfile
This commit improves the c-ares and curl build process to use cmake instead. This is a much better choice for docker container. We do not require the features GNU Make provides. CMake should also be more stable for testing pull requests on GitHub.
It also upgrades the c-ares and curl version to receive the latest bug fixes and performance changes. There's been a huge leap forward since the older changes. Put simple, curl 8 is faster. https://daniel.haxx.se/blog/2023/04/28/curl-8-is-faster/
=> Improve c-ares & curl build process

Dockerfile
- Compile everything with level 3 optimizations.
- Disable warnings for the `rtorrent` software stack to prevent overflows and reduce overall ARM build time.
- Fix critical issues with `xml-rpc` and `libtorrent` not applying the build flags. 
- Add build flags to `mktorrent` and change compiler to `gcc`.
- Fix configure params. Spaces are not allowed.
- Drop `c++` support for `xmlrpc`. (not required)
=> Build fixes & improvements

Dockerfile, README.md, patches/libtorrent/libtorrent-scanf-0.13.8.patch, patches/libtorrent/libtorrent-udns-0.13.8.patch
This pull request implements the `UDNS` library into `libtorrent` for asynchronous DNS requests on UDP trackers. The current `c-ares` support is limited to TCP trackers.
It resolves stability issues with the `rTorrent` software stack where UDP trackers run synchronously by default. With a large number of torrents, the software will give out and fail to seed torrents.
It also caches the result of `sscanf` into vector object, to avoid calling it thousands of times on broken trackers. This prevents the software from crashing and increases overall performance.
=> rTorrent: Implement UDNS support

Dockerfile, patches/rtorrent/rtorrent-ml-cg-fix.patch, patches/rtorrent/rtorrent-ml-cui-fix.patch, patches/rtorrent/rtorrent-ml-dc-fix.patch
This patch resolves critical memory leaks with the rTorrent software, that can cause an out of memory condition to happen. It has been tested for months and has demonstrated proven memory stability for rTorrent.
=> rTorrent: Resolve memory leaks

Dockerfile
rTorrent requires the usage of aligned memory access on all platforms (x86 and ARM) to prevent a memory access crash from happening. As such, we need to configure libtorrent with `--enable-aligned` to enable the feature.
This is also more efficient for CPU usage at the cost of slightly more memory consumption.  However, due to the relatively small usage of memory, all platforms will benefit.
More information can be found here: https://github.com/rakshasa/libtorrent/issues/244
=> rTorrent: Resolve memory access crash

Dockerfile
The `mime_content_type` function is part of the fileinfo extension:
https://github.com/Novik/ruTorrent/blob/2d67a00b4fde90b4a652c130ed76ac2fc4383fb3/plugins/tracklabels/action.php#L66
Icon upload now works after adding this package.
=> Add php82-fileinfo package

rootfs/etc/cont-init.d/03-config.sh
We **must** add `$useInternalHybrid = true;` to the torrent creator configuration file for `ruTorrent v4.3.0` compatibility.
=> ruTorrent v4.3.0 fix

rootfs/etc/cont-init.d/03-config.sh
Users are receiving 404 errors during version upgrades. We need to disallow removing the httprpc plugin because it's required for ruTorrent v4.3+ operation. See #345.
=> ruTorrent: Do not permit core plugin removal of httprpc

rootfs/tpls/etc/nginx/conf.d/rpc.conf, rootfs/tpls/etc/nginx/conf.d/rutorrent.conf, rootfs/tpls/etc/nginx/conf.d/webdav.conf
fixes #348
There is no point in supporting IPV6 on this docker container. IPV4 is required anyways for rTorrent to function properly.
If the user disables loading the IPV6 kernel module at boot time, the docker container will fail to initialize if nginx is listening for IPV6.
=> nginx: Disable listening for IPV6

Dockerfile
It was moved to GitHub. 
Example link:
https://github.com/c-ares/c-ares/releases/download/cares-1_24_0/c-ares-1.24.0.tar.gz
`${CARES_VERSION//\./\_}` replaces all the dots in the version string with underscore to build the new download URL.
=> docker: Fix c-ares download link

rootfs/tpls/etc/rtorrent/.rtlocal.rc
fixes #281
This commit schedules the session save when a new download is inserted. The benefit if we can thread it as a background task. This avoids disruptions during startup and increases overall speed. The unique hash of the torrent is used as the schedule handle, to prevent accidently overwriting the task. It runs once and immediately.
=> rTorrent: Schedule torrent session save as background task

rootfs/tpls/etc/rtorrent/.rtlocal.rc
- Only run when a new download is inserted (not at startup). This avoids writing the entire torrent session library to disk at startup. We change the event from `event.download.inserted` to `event.download.inserted_new` to improve performance.
- Remove unnecessary 2nd key. The `method.set_key` command does not take a method name. As a result, we should not provide it to avoid warnings. We only need to provide the schedule key.
=> rTorrent: Optimize session saving for new torrents

Dockerfile
This new release contains numerous bug fixes since the previous version. It also contain a performance increase for the purpose of rTorrent. DNS queries are now cached for 1 hour to avoid repetitive lookups. This will improve TCP tracker update performance.
=> Upgrade to c-ares 1.31

Dockerfile, README.md
Allows for near instantaneous torrent creation by multi-threading the hashing process, provided disk resources are available. We must apply these options directly to the Makefile. This software will not accept environment variables passed by GNU make.
- Remove unnecessary redirect with git clone.
- Properly apply compiler and build flags.
- Use pthreads and openssl for multi-threading.
=> Upgrade mktorrent build script

Dockerfile
**The full changelog between the last tag can be viewed here.**
**Full Changelog**: https://github.com/stickz/rtorrent/compare/v5.1-0.9.8-0.13.8...v5.3-0.9.8-0.13.8
The `--disable-instrumentation` configure option for libtorrent now it's works properly. The threads still have instrumentation, so they work properly. All other source code instrumentation is disabled at compile time. This allows the software to perform tasks in the most efficient order and reduces scheduling overhead.
This configure option is an intermediary step. It's highly recommended to use it. In the future, instrumentation will be removed entirely for non-threaded tasks. In the very unlikely event a regression is found, please file an issue report. 
* libtorrent: Optimize unsigned int datatypes by @stickz in …
=> Upgrade to rTorrent v5.3

Dockerfile
**Full Changelog**: https://github.com/stickz/rtorrent/compare/v5.3-0.9.8-0.13.8...v6.0-0.9.8-0.13.8
This release includes a rewrite of the UDNS interface for libtorrent to increase performance and stability of UDP trackers. It can be enabled by configuring libtorrent with `--enable-udns`. It is now more stable than rakshasa's resolver interface.
1. The resolver callbacks are now handled by the connection manager to avoid a crash when the UDP tracker becomes invalid.
2. The UDP trackers are now optimized with a fast-path to IPV4, since the UDNS interface can only support one DNS resolution method a time. This significantly reduces the amount of CPU instructions required to update a UDP tracker and avoids redundant network sockets.
This release includes two hash threads instead of one to …
=> Upgrade to rTorrent v6.0

Dockerfile
This commit removes unused code from the xmlrpc-c compile to reduce the binary size.
=> xmlrpc-c: Remove unused code

Dockerfile
This commit bumps the ruTorrent version to 5.1 for mobile support. It also retrieves and builds the required dump torrent dependency.
**Full Changelog**: https://github.com/Novik/ruTorrent/compare/v4.3.6...v5.1.0
=> Add ruTorrent v5.1 support

Dockerfile
This release contains a few minor bug fixes and performance changes.
* Fix compile with GCC 14 by @stickz in https://github.com/stickz/rtorrent/commit/52693ae5788a41e046b77d55afd0f40a8fea3414
* Drop CPPUNIT dependency by @stickz in https://github.com/stickz/rtorrent/commit/6f7bdfd9a916caa1da19845e99ee5c4fc6af5922
* Only write piece timestamp when required by @stickz in https://github.com/stickz/rtorrent/commit/f671ae97e54f38ae91c20c668ffe581e60abb46b
* Fix Handshake read buffer size by @stickz in https://github.com/stickz/rtorrent/commit/faede8af61804bad1d89ba9654ced467ec4f7328
* Fix memory access compile warning by @stickz in https://github.com/stickz/rtorrent/commit/33495c44a8354c35877b5139c1ffa8e64193ed5e
**Full Changelog**: https://github.com/stickz/rtorrent/compare/v6.1-0.9.8-0.13.8.. …
=> rTorrent: Upgrade to v6.2

Dockerfile
This pull request upgrades to Alpine v3.21 for GCC 14. This contains additional performance improvements for the rTorrent stack.
I would like to stay on PHP 8.3 for now, until PHP 8.4 receives more hotfixes. Furthermore, we need to make sure they are no ruTorrent issues with PHP 8.3 before upgrading to PHP 8.4.
=> Alpine: Upgrade to v3.21

Dockerfile
This a major new release that provides the option to replace xmlrpc-c with tinyxml2. Tinyxml2 is 2 to 3 times faster for smaller responses and up to 30 times faster for large responses than it's xmlrpc-c counterpart. It is fully compatible with ruTorrent. It results in a significant reduction of in overhead, by eliminating the requirement for xmlrpc-c and it's stack of dependences.
To use simply configure rTorrent `--with-xmlrpc-tinyxml2` instead of `--with-xmlrpc-c`. This will be the default option in the near future!
xmlrpc-c
```
Benchmark               Time             CPU   Iterations
---------------------------------------------------------
small_response       3417 ns         3413 ns       204332
large_response   46159260 ns     46074301 ns           15
```
tinyxml2:
```
Benchmark …
```
=> rTorrent: Upgrade to v7.0

.github/workflows/test.yml
=> ci; update bake-action to v6

Dockerfile, README.md
Support for rTorrent rakshasa has resumed. rTorrent stickz is being deprecated in favour of this new stable rakshasa release. It has tinyxml2 and UDNS bundled with the software. Requires #438 . closes #431 .
https://github.com/rakshasa/rtorrent/releases/tag/v0.15.3
The purpose of rtorrent stickz was due to dropped support of rtorrent rakshasa. It contained UDNS for stability purposes. Now that rakshasa has resumed support, bundled UDNS and made a stable release, there is no reason left to maintain rtorrent stickz.
=> rTorrent: Switch to rakshasa v0.15.3

Dockerfile
1. Upgrades c-ares from `1.34.4` to `1.34.5` for bug fixes. 
2. Upgrades cURL from `8.11.1` to `8.12.1`. The next minor release with bug fixes for c-ares.
3. Add new libpsl-dev requirement for cURL.
=> Upgrade to c-ares & curl

Dockerfile, patches/libtorrent/libtorrent-0.15.3-resume-fix.patch
This commit patches two rTorrent `0.15.3` software crashes. These changes have been linked and merged upstream.
=> rTorrent: Patch two software crashes
